version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
  
  pre_build:
    commands:
      - echo "Pre-build preparation..."
      - echo "Verifying test results from previous test stage..."
      - |
        if [ -f "test-results.json" ]; then
          echo "Test results found, validating before proceeding..."
          TEST_RESULTS=$(cat test-results.json)
          echo "Test Results: $TEST_RESULTS"
          
          # Check if tests passed
          TESTS_PASSED=$(node -e "const results=JSON.parse(process.env.TEST_RESULTS); console.log(results.passed ? 'true' : 'false');")
          if [ "$TESTS_PASSED" = "true" ]; then
            echo "Test validation successful, proceeding with build"
          else
            echo "Test validation failed! Check test reports for details."
            exit 1
          fi
        else
          echo "No test results found from test stage. Tests must have been skipped or run separately."
          echo "Continuing build process but be aware that tests may not have run successfully."
        fi
      - echo "Pre-build phase completed on `date`"
  
  build:
    commands:
      - echo "Build started on `date`"
      # Update the build date in the index.html file
      - BUILD_DATE=$(date +"%B %d, %Y")
      - echo "Setting build date to $BUILD_DATE"
      - sed -i "s|<span id=\"build-date\">.*</span>|<span id=\"build-date\">$BUILD_DATE</span>|g" index.html
      # You can add more build commands here, like bundling or minification
      - echo "Build completed on `date`"
  
  post_build:
    commands:
      - echo "Post-build phase started on `date`"
      # Add any post-build commands here if needed
      - echo "Post-build phase completed on `date`"

artifacts:
  files:
    - index.html
    - css/**/*
    - js/**/*
    - images/**/*
    - favicon.ico
    - buildspec.yml
    - appspec.yml
    - scripts/**/*
  discard-paths: no

reports:
  build-reports:
    files:
      - 'build-report.json'
    file-format: 'JSON'

cache:
  paths:
    - 'node_modules/**/*'
