version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g jest
  
  pre_build:
    commands:
      - echo "Running tests..."
      - echo "Running unit tests..."
      - npm test -- --testPathPattern=tests/unit
      - echo "Running integration tests..."
      - npm test -- --testPathPattern=tests/integration
      - echo "Generating test coverage report..."
      - npm run test:coverage
      - echo "Pre-build phase completed on `date`"
  
  build:
    commands:
      - echo "Build started on `date`"
      # Update the build date in the index.html file
      - BUILD_DATE=$(date +"%B %d, %Y")
      - echo "Setting build date to $BUILD_DATE"
      - sed -i "s|<span id=\"build-date\">.*</span>|<span id=\"build-date\">$BUILD_DATE</span>|g" index.html
      # You can add more build commands here, like bundling or minification
      - echo "Build completed on `date`"
  
  post_build:
    commands:
      - echo "Post-build phase started on `date`"
      # Add any post-build commands here if needed
      - echo "Post-build phase completed on `date`"

artifacts:
  files:
    - index.html
    - css/**/*
    - js/**/*
    - images/**/*
    - favicon.ico
    - buildspec.yml
    - appspec.yml
    - scripts/**/*
  discard-paths: no

reports:
  jest-reports:
    files:
      - 'coverage/clover.xml'
    file-format: 'CLOVERXML'

cache:
  paths:
    - 'node_modules/**/*'
